Ankit/add composio agent
video-db/Director pull request #71
Opened 2024-11-15 13:51 UTC by ankit-v2-3

- Add Composio Agent and Tool.

2024-11-18 18:01 UTC, ashish-spext commented
1. We should have Text Component of composio response for v1, for cases like below.
![image](https://github.com/user-attachments/assets/37622d05-54aa-48ab-811f-006aeb0765b0)


2. We should make easy for users to add tools which don't require API Keys (e.g hackernews)
Maybe let's add them in .env.sample as commented line?

2024-11-19 11:55 UTC, ankit-v2-3 commented on backend/director/agents/composio.py
> +        self.description = f'The Composio agent is used to run tasks related to apps like {os.getenv("COMPOSIO_APPS", ["GMAIL"])} '
Yeah, removed gmail

2024-11-19 11:57 UTC, ankit-v2-3 commented
Response from Composio is not readable, so not adding into Text component.

2024-11-19 16:13 UTC, ankit-v2-3 commented
Added additional LLM call to format Composio response. Can you please test the experience?

2024-11-20 09:03 UTC, ashish-spext requested changes

2024-11-20 09:20 UTC, ashish-spext approved these changes

2024-11-20 09:20 UTC, merged